### ISSUE TITLE
Issue with STRUMPACK: Error with factor method in HSSMatrix

### ISSUE THREAD

**Issue by kdMoura** [StefanoCipolla/Strumpack_ADMM#1]
Hi, 

I encountered an error while trying to compile the project.
Have you ever faced the following problem at any point?

```
[ 50%] Building CXX object CMakeFiles/SVM_ADMM.dir/KernelSVM_final.cpp.o
/Strumpack_ADMM-main/KernelSVM_final.cpp: In function ‘int main(int, char**)’:
/Strumpack_ADMM-main/KernelSVM_final.cpp:138:9: error: ‘void ULV’ has incomplete type
  138 |    auto ULV = H.factor();
      |         ^~~
make[2]: *** [CMakeFiles/SVM_ADMM.dir/build.make:76: CMakeFiles/SVM_ADMM.dir/KernelSVM_final.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:83: CMakeFiles/SVM_ADMM.dir/all] Error 2
make: *** [Makefile:91: all] Error 2
```
It seems like the `factor` method in the `HSSMatrix` class is being treated as a void function, which contradicts the documentation provided [here](https://portal.nersc.gov/project/sparse/strumpack/v5.0.0/classstrumpack_1_1HSS_1_1HSSMatrix.html).

I noticed that you used STRUMPACK version 6.3.1, but I could only successfully install the GitHub version.

Do you have any insights on how to resolve this issue? Any help or suggestions would be greatly appreciated.

Thanks!

**Comment by StefanoCipolla** [comment]
Hi,

Unfortunately I do not know what is happening.

Probably is connected with the Strumpack version.

Have you tried to ask to the Strumpack team?

Stefano

**Comment by kdMoura** [comment]
I also suspect that the issue is related to the Strumpack's version. Will probably check this out with them. 
Thank you for your attention!
